### ISSUE TITLE
Condition value text overlapping in narrow screen widths

### ISSUE THREAD

**Issue by colinrsmall** [ModernVivo/mv-frontend#1]
Condition value texts are overlapping at narrow browser widths (see screenshot). At narrower widths, can we switch the condition values from being listed in a table to being listed in a single list?

Issue:
<img width="1140" alt="image" src="https://github.com/ModernVivo/mv-frontend/assets/20507041/6dc9e3d4-d683-47af-ab0c-e8554aeab8ee">

Proposed solution design:
![image](https://github.com/ModernVivo/mv-frontend/assets/20507041/f6cdc3cd-da2c-4aec-9461-a0b4dccde33f)

**Comment by huylesitdn** [comment]
@colinrsmall please new commit

**Comment by colinrsmall** [comment]
Thanks Huy! Ended up changing the breakpoint from lg to xl but it's looking great now.
