### ISSUE TITLE
Create filter box for author affiliations

### ISSUE THREAD

**Issue by colinrsmall** [ModernVivo/mv-frontend#14]
Currently, users can only filter search results by their condition values. We would like to add a filter box for author affiliation:

![image](https://github.com/ModernVivo/mv-frontend/assets/20507041/1da3f40d-193d-4afd-b62b-ecf395022ad1)

Details

- Internally, each paper's author affiliation is categorized into three types: "industry," "academia," and "government."
- The "Affiliation Filters" box will always contain two sub-filter-boxes: "General" and "Specific Affiliation."
- - The "General" sub-box will always feature three checkboxes: "Industry," "Academia," and "Government," representing the three types of affiliation.
- - The "Specific Affiliation" sub-box will include a checkbox for each affiliation of the authors of papers in the search results.
- For instance, if the user selects an in vivo model with three papers in the database, and the authors of those papers have affiliations such as "University of New Hampshire," "University of Washington," and "Pfizer," then the "Specific Affiliation" sub-box should display checkboxes for each of these affiliations. 
- The affiliation for each author is stored in the affiliation attribute of each Author model in the backend (https://github.com/ModernVivo/mv_backend/blob/993403a4e83dd5d02845147e5de454e239be3cc7/src/core/models.py#L29)
- The affiliation type and name can be accessed in the Affiliation model in the backend (https://github.com/ModernVivo/mv_backend/blob/993403a4e83dd5d02845147e5de454e239be3cc7/src/core/models.py#L17)
- The "Affiliation Filters" box should always appear on the search results page

**Comment by huylesitdn** [comment]
- The "Specific Affiliation" sub-box will include a checkbox for each affiliation of the authors of papers in the search results.
=> Specific Affiliation list will be changes when paper results change, right?

**Comment by colinrsmall** [comment]
Yes
