### ISSUE TITLE
Model search bar should only show options where usable=True

### ISSUE THREAD

**Issue by colinrsmall** [ModernVivo/mv-frontend#8]
The search bar on the main page should only list options to users where usable=True for the model. I couldn't figure out how to alter the getModels query that runs on the frontend, so for now I hardcoded it in the backend:

https://github.com/ModernVivo/mv_backend/blob/94515638eda3b8b2f066b029b175427285606001/src/core/views.py#L32

We should reset the queryset to InvivoModel.objects.all() and instead have the frontend search only for models where usable=True.

**Comment by huylesitdn** [comment]
add `usable: "True"` to `useGetModelQuery`
